on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build on master
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v19.0.0
      with:
        node-version: ${{ matrix.node_version }}
    - name: npm install and build
      run: |
        npm install
        npm run build
