on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build on master
    uses: nodejs@19.0.0
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest]
    steps:
    - name: Use Node.js ${{ matrix.node_version }}
      with:
        node-version: ${{ matrix.node_version }}
    - name: npm install and build
      run: |
        npm install
        npm run build
